apiVersion: v1
kind: Service
metadata:
  labels:
    app: mordor-bootnode-2
  name: mordor-bootnode-2
  namespace: ethercluster
  annotations:
    cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: mordor-bootnode-2
  ports:
  - name: default
    protocol: TCP
    port:  8080
    targetPort: 8080
  - name: rpc-endpoint
    port: 8545
    protocol: TCP
    targetPort: 8545
  - name: bootnode
    port: 30303
    protocol: TCP
    targetPort: 30303
  - name: ws-endpoint
    port: 8546
    protocol: TCP
    targetPort: 8546
  type: LoadBalancer
  sessionAffinity: ClientIP
