apiVersion: v1
kind: Service
metadata:
  labels:
    app: ethercluster-site
  name: ethercluster-site
  namespace: ethercluster
  annotations:
    cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'
spec:
  selector:
    app: ethercluster-site
  ports:
  - name: site
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
  sessionAffinity: ClientIP
