kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mordor-bootnode-2-ssd
  namespace: ethercluster
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zones: us-central1-c
reclaimPolicy: Retain
