apiVersion: v1
kind: Service
metadata:
  labels:
    app: classic-metamask 
  name: classic-metamask
  namespace: ethercluster
  annotations:
    cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: classic-metamask 
  ports:
  - name: default
    protocol: TCP
    port:  8080 
    targetPort: 8080
  - name: rpc-endpoint
    port: 8545 
    protocol: TCP
    targetPort: 8545
  - name: ws-endpoint
    port: 8546
    protocol: TCP
    targetPort: 8546
  - name: https
    port: 443 
    protocol: TCP
    targetPort: 443
  type: LoadBalancer
  sessionAffinity: ClientIP
