kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nazgul-mgeth-ssd
  namespace: ethercluster 
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zones: us-central1-c
reclaimPolicy: Retain
