apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: classic-besu 
  namespace: ethercluster
  labels:
    app: classic-besu
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: classic-besu
  serviceName: classic-besu
  template:
    metadata:
      name: classic-besu
      labels:
        app: classic-besu
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: besu
          image: "hyperledger/besu:latest"
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          args: 
          - "--network=classic"
          - "--data-path=/classic-besu-data"
          - "--node-private-key-file=/classic-besu-data/keys"
          - "--rpc-http-enabled" 
          - "--rpc-ws-enabled"
          ports:
            - containerPort: 8545
              protocol: TCP
              name: rpc-port
            - containerPort: 8546
              protocol: TCP
              name: ws-port
            - containerPort: 443
              protocol: TCP
              name: https
          readinessProbe:
            httpGet:
              port: 8545
              path: /readiness
            initialDelaySeconds: 9000
            periodSeconds: 1800
          livenessProbe:
            httpGet:
              port: 8545
              path: /liveness
            initialDelaySeconds: 9000
            periodSeconds: 1800
          volumeMounts:
            - name: classic-besu-data
              mountPath: /classic-besu-data
      volumes:
       - name: classic-besu-data
  volumeClaimTemplates:
    - metadata:
        name: classic-besu-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "classic-besu-ssd"
        resources:
          requests:
            storage: 50Gi
