apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nazgul-parity 
  namespace: ethercluster
  labels:
    app: nazgul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nazgul
  serviceName: nazgul
  template:
    metadata:
      name: nazgul-parity
      labels:
        app: nazgul
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: parity
          image: "parity/parity:v2.5.6-stable"
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          args: ["--chain", "/nazgul-parity-config/parity.json", "--nat", "extip:35.192.211.157"]
          ports:
            - containerPort: 8545
              protocol: TCP
              name: rpc-port
          volumeMounts:
            - name: nazgul-parity-config
              mountPath: /nazgul-parity-config
              readOnly: true
            - name: nazgul-parity-data
              mountPath: /nazgul-parity-data
        - name: ethnetintel
          image: kairen/ethnetintel
          env:
          - name: NAME_PREFIX
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: WS_SERVER
            value: "classic-stats.default.svc.cluster.local:3000"
          - name: WS_SECRET
            value: "12qw34er"
          - name: RPC_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: RPC_PORT
            value: "8545"
      volumes:
      - name: nazgul-parity-config
        secret:
          secretName: nazgul-parity-config
  volumeClaimTemplates:
    - metadata:
        name: nazgul-parity-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "nazgul-parity-ssd"
        resources:
          requests:
            storage: 50Gi
